Adding support for handling MAPAXES and MAPUNITS
OPM/opm-common pull request #2617
Opened 2021-08-19 13:29 UTC by tskille

adding support in class EGrid for reading MAPAXES and MAPUNITS from egrid file

2021-08-19 13:30 UTC, tskille commented
This is now ready for review.

2021-08-19 13:31 UTC, akva2 requested changes

2021-08-19 13:31 UTC, akva2 commented on opm/io/eclipse/EGrid.hpp
> +    std::vector<float> get_mapaxes() const { return m_mapaxes; }
why the copy?

2021-08-19 13:31 UTC, akva2 commented on opm/io/eclipse/EGrid.hpp
> +    std::string get_mapunits() const { return m_mapunits; }
why the copy?

2021-08-19 13:31 UTC, akva2 commented on src/opm/io/eclipse/EGrid.cpp
> +    m_mapunits = "";
strings are default empty.

2021-08-19 13:36 UTC, tskille commented on opm/io/eclipse/EGrid.hpp
> +    std::string get_mapunits() const { return m_mapunits; }
fixed const ref on both.

2021-08-19 13:36 UTC, tskille commented on src/opm/io/eclipse/EGrid.cpp
> +    m_mapunits = "";
deleted line.

2021-08-19 13:37 UTC, akva2 commented
jenkins build this please

2021-08-20 10:27 UTC, akva2 approved these changes

2021-08-20 11:12 UTC, joakim-hove commented
Then we merge :-)

2021-08-20 11:12 UTC, merged