Support for SGWFN sat functions (format type 2)
OPM/opm-common pull request #3705
Opened 2023-10-10 19:02 UTC by daavid00

Although in the manual it is stated that SGWFN is supported, the simulator ends with
```
Simulation aborted as program threw an unexpected exception: Could not allocate the problem: Saturation functions must be specified using either family 1 or family 2 keywords
Use either SGOF (or SLGOF) and/or SWOF or SGFN/SWFN and SOF2/SOF3
```
This PR adds support for this keyword. It has been tested using the first table in [SGOF_R.INCL](https://github.com/OPM/opm-tests/blob/master/three_phase_relperm/SGOF_R.INCL) in two CO2STORE decks (the first one with GAS OIL SGOF and the second one with GAS WATER SGWFN (see attached zip)), giving the same results.
![sgwfn_vs_sgof](https://github.com/OPM/opm-common/assets/61784809/b45e960b-60a9-4237-86c0-e770b5106a8b)
[Test_sgwfn_sgof.zip](https://github.com/OPM/opm-common/files/12860948/Test_sgwfn_sgof.zip)

2023-10-11 14:37 UTC, bska requested changes
Overall this is okay, but I really think you need to look closer at the water part of this contribution.  Translation from gas to water saturation appear to be missing in a number of places.

2023-10-11 14:37 UTC, bska commented on src/opm/output/eclipse/Tables.cpp
> +                                      linTable.column(tableID, primID, 1));
I think you need to do more than this.  The first column in the result array is supposed to be `Sw` in increasing order and you can't just copy `Sg` into that and use it directly.  The second column is supposed to be `krgw` in increasing order.  You'll have to use something along the lines of
```C++
{
    const auto& Sg = t.getSgColumn();
    std::transform(std::rbegin(Sg), std::rend(Sg),
                   linTable.column(tableID, primID, 0),
                   [](const auto sg) { return 1.0 - sg; });
}

{
    const auto& krgw = t.getKrgwColumn();
    detail::outputRelperm(std::rbegin(krgw), std::rend(krgw), tolcrit,
                          linTable.column(tableID, primID, 1));
}
````
instead.

2023-10-11 14:37 UTC, bska commented on src/opm/output/eclipse/Tables.cpp
> +        /// SWFN tables for all saturation function regions from Family One
Tiny nit: This should say "Family Two" instead.

2023-10-11 14:37 UTC, bska commented on src/opm/input/eclipse/EclipseState/Runspec.cpp
> +                     deck.hasKeyword<Opm::ParserKeywords::SGWFN>())) ||
You should add a similar change to the `wat` case.

2023-10-11 14:37 UTC, bska commented on src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
> +    double critical_water_sgwfn(const T& table, const double tolcrit)
This should not be a template.  It should take exactly an `SwgfnTable` as its first argument.

2023-10-11 14:37 UTC, bska commented on src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
> +                                      table.getKrgwColumn(), tolcrit);
This will return `Sg` at the critical relative permeability level.  You'll have to transform that into a water saturation (`1 - Sg`) at some point.

2023-10-11 14:56 UTC, bska commented
I also want to see a suite of unit tests added for `SWGFN`, e.g., in [`FieldPropsTests.cpp`](https://github.com/OPM/opm-common/blob/a4f9fb1dd855d7c9183b095f4b3194ae43786413/tests/parser/FieldPropsTests.cpp#L1088) to demonstrate that we get the expected end-point and function values from the initialisation code in this case.

2023-10-11 21:43 UTC, daavid00 commented
> I also want to see a suite of unit tests added for `SWGFN`, e.g., in [`FieldPropsTests.cpp`](https://github.com/OPM/opm-common/blob/a4f9fb1dd855d7c9183b095f4b3194ae43786413/tests/parser/FieldPropsTests.cpp#L1088) to demonstrate that we get the expected end-point and function values from the initialisation code in this case.

Many thanks @bska for your review. I have made the requested changes and also added a test. Please let me know if this needs further corrections.

2023-10-12 07:12 UTC, GitPaean commented
jenkins build this please

2023-10-12 14:26 UTC, bska commented
jenkins build this please

2023-10-13 08:29 UTC, bska approved these changes
Thank you for the updates.  This looks good to me now and I'll merge into master.

2023-10-13 08:30 UTC, merged