only set well temperature if WTEMP or WINJTEMP is set
OPM/opm-common pull request #4152
Opened 2024-07-29 09:26 UTC by totto82

Make it possible to check if temperature is defaulted or not. For CO2STORE runs we would like to use the perforation temperature as default if WTEMP or WINJTEMP is not set. In particular this apply to isothermal runs

2024-07-29 09:29 UTC, totto82 commented
jenkins build this opm-simulators=5490 please

2024-07-30 06:30 UTC, totto82 commented
jenkins build this opm-simulators=5490 please

2024-07-30 13:56 UTC, totto82 commented
jenkins build this opm-simulators=5490 please

2024-07-31 09:37 UTC, GitPaean requested changes
The code looks working for the assumption it brings in.  My comments are mostly related to the assumption whether we should emphasize the temperature is only related to injectors.

2024-07-31 09:37 UTC, GitPaean commented on opm/input/eclipse/Schedule/Well/Well.hpp
> +    std::optional<double> well_temperature;
Will this temperature ever be related to producers? If not, maybe we should change the variable name to be inj_temperature, something like that so we make sure it is only related to injectors.

2024-07-31 09:37 UTC, GitPaean commented on opm/input/eclipse/Schedule/Well/Well.cpp
> +    return this->well_temperature.has_value();
If the assumption that the temperature is only related to injectors stands, the function names `hasTemperature` and `tempature` can also change to reflect that the temperature is for injectors only. (there is a dedicated function isInjector() defined, which can be better for readability?) 

And we can check production/injection types in this function. 

And the if condition above `if (!this->wtype.producer() && this->well_temperature)` can become 
`if (this->hasTemperature) or `if (this->hasInjTemperature)` if the function name changes.

2024-07-31 09:37 UTC, GitPaean commented on opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp
> +            const double current_temp = well.hasTemperature()? well.temperature(): 0.0;
since we changes to use std::optional for the well (injection) temperature, should we make sure it is std::nullopt for producers?

2024-08-01 09:24 UTC, totto82 commented
jenkins build this opm-simulators=5490 please

2024-08-01 12:08 UTC, totto82 commented
Thanks for the review. I have followed your suggestions. The reference data needs an update since the reservoir injection rate has changed.

2024-08-01 12:09 UTC, totto82 commented
jenkins build this opm-simulators=5490 update_data please

2024-08-01 22:52 UTC, GitPaean commented
jenkins build this opm-simulators=5490 opm-tests=1201 please

2024-08-02 06:33 UTC, merged